### ISSUE TITLE
File output set up

### ISSUE THREAD

**Issue by alkaj** [spiritix/html-to-pdf#4]
Hi, @spiritix I am trying to use this wrapper to generate pdf from my PHP page, but I can't find any documentation on how to save a file into a particular folder with the FileOutput just see in the usage example how to make it available to download, I would like it if you can point me out some resources so that I can make it clear. 
Thanks for your work and your time.

**Comment by spiritix** [comment]
Hi, something like this should work:

```php
use Spiritix\HtmlToPdf\Converter;
use Spiritix\HtmlToPdf\Input\UrlInput;
use Spiritix\HtmlToPdf\Output\FileOutput;

$input = new UrlInput();
$input->setUrl('https://www.google.com');

$converter = new Converter($input, new FileOutput());

$converter->setOption('n');
$converter->setOption('d', '300');

$converter->setOptions([
    'no-background',
    'margin-bottom' => '100',
    'margin-top' => '100',
]);

$output = $converter->convert();
$output->store('path/to/file.pdf');
```
